version = 1

test_patterns = ["*_test.go"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/Cyb3r-Jak3/go_har"]

[[analyzers]]
name = "test-coverage"
enabled = true