run:
  modules-download-mode: readonly

issues:
  exclude-dirs-use-default: true

linters:
  enable:
    - staticcheck
    - dupl
    - govet
    - goconst
    - tenv
    - ineffassign
    - bodyclose
    - gosec
    - prealloc
    - unused
    - gofmt
    - revive
    - stylecheck
    - whitespace
    - goprintffuncname
    - gosimple
    - gocyclo
    - goimports
    - misspell
    - godot
    - reassign
    - unconvert
    - nilerr
    - govet

output:
  formats:
    - format: colored-line-number
