lint:
	golangci-lint run --config .golangci-lint.yml ./...

test:
	go test -race -covermode=atomic -v -coverprofile="coverage.out" ./...
	go tool cover -func="coverage.out"

scan:
	gosec -no-fail -fmt sarif -out security.sarif ./...

bench:
	go test -bench=. ./...