lint:
	go vet ./...
	golangci-lint run -E revive,gofmt ./...

test:
	go test -race -v -coverprofile="c.out" ./...
	go tool cover -func="c.out"

scan:
	gosec -no-fail -fmt sarif -out security.sarif ./...

bench:
	go test -bench=. ./...