name: Go

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'go.sum'
      - 'go.mod'
      - '**.go'
      - .github/workflows/main.yml
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ '1.18', '1.19', '1.20' ]
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Vet
        run: go vet .

      - name: Test
        run: make test

      - name: Run Simple Example
        run: go run ./example/simple/main.go

      - name: Report to Deepsource
        if: ${{ runner.os == 'Linux' && env.DEEPSOURCE_DSN != null }}
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key go --value-file ./c.out
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
