name: Go

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          golint -set_exit_status .
      - name: Vet
        run: go vet .
      - name: Test
        run: go test --cover .
      - name: Build
        run: go build -v .
