name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Link
        run: |
          go get -u golang.org/x/lint/golint
          golint .
      - name: Build
        run: go build -v .
      - name: Test
        run: go test --cover .
