name: Go

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.14', '1.13', '1.12', '1.11' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          golint -set_exit_status .
      - name: Vet
        run: go vet .
      - name: Test
        run: go test --cover .
